# Project: Alter Molecular Structures Using Python
In the remaining time that we have, we will be using Python to take a starting structure of a molecule (benzene) and then shifting and rotating the molecule in three dimensional space. This work will be in preparation for the afternoon's project: __Adapt python code to create a system of user-defined number of benzene molecules with random orientations and no overlap between molecules.__ 

## Before beginning to code, we should visualize the benzene molecule.
We can visualize the molecular geometry of benzene using VMD:

vmd Benzene_structure/benzene.xyz

Additionally, we should look at the data file (benzene.xyz) to see the format of the file.

# Translate the benzene molecule in space
## Code Outline: 
1) Read in the xyz file, saving atom names and original positions.

2) Shift the original atomic positions by a user-defined value.

3) Output an xyz file with the new positions.

### User Defined variables

In [18]:
import numpy as np

shift = 5.00 # units of angstroms
xyzInputFile = 'Benzene_structure/benzene.xyz'
xyzOutputFile = 'Benzene_structure/benzene_shift_5.0.xyz'

### Read an XYZ file

In [25]:
xyz_file = open('Benzene_structure/benzene.xyz','r')
lineCount = 0
atomCount = 0
atomNames = []

for line in xyz_file:
    if lineCount == 0:
        nAtoms = int(line)
        positions = np.empty((nAtoms,3),dtype=float) # np.empty creates an empty numpy.ndarray that can be filled
    elif lineCount > 1:  # we want to skip over the 2nd line (lineCount = 1) because it holds no important information
        split_line = line.split()
        atomNames.append(split_line[0])
        for k in range(3):
            positions[atomCount,k] = float(split_line[k+1])
        atomCount += 1
    lineCount += 1

xyz_file.close()

print atomCount, lineCount
print atomNames
print positions

12 14
['C1', 'H1', 'C2', 'H2', 'C3', 'H3', 'C4', 'H4', 'C5', 'H5', 'C6', 'H6']
[[ 1.45   0.     0.   ]
 [ 2.45   0.     0.   ]
 [ 0.75  -1.212  0.   ]
 [ 1.25  -2.078  0.   ]
 [-0.75  -1.212  0.   ]
 [-1.25  -2.078  0.   ]
 [-1.45   0.     0.   ]
 [-2.45   0.     0.   ]
 [-0.75   1.212  0.   ]
 [-1.25   2.078  0.   ]
 [ 0.75   1.212  0.   ]
 [ 1.25   2.078  0.   ]]


### Shift atomic positions

In [26]:
positions += shift
print positions

[[ 6.45   5.     5.   ]
 [ 7.45   5.     5.   ]
 [ 5.75   3.788  5.   ]
 [ 6.25   2.922  5.   ]
 [ 4.25   3.788  5.   ]
 [ 3.75   2.922  5.   ]
 [ 3.55   5.     5.   ]
 [ 2.55   5.     5.   ]
 [ 4.25   6.212  5.   ]
 [ 3.75   7.078  5.   ]
 [ 5.75   6.212  5.   ]
 [ 6.25   7.078  5.   ]]


### Output the new positions

In [27]:
outputFile = open(xyzOutputFile,'w')
outputFile.write('%10d\n'%(nAtoms))
outputFile.write('Translated Molecule\n')
for atom in range(nAtoms):
    outputFile.write('%5s %10.5f %10.5f %10.5f\n'%(atomNames[atom],positions[atom,0],positions[atom,1],positions[atom,2]))
outputFile.close()

### How does this molecule look? What did we just do?

# Rotate the benzene molecule in space 
## Code Outline: 
1) Read in the xyz file, saving atom names and original positions.

2) With a user-defined angle of rotation, perform rotations of the molecule in the x,y, and z dimensions.

3) Output an xyz file with the new atomic positions.

### User Defined variables

In [83]:
import numpy as np
import rotation_functions

degrees_to_radians = np.pi/180.

xyzInputFile = 'Benzene_structure/benzene.xyz'
xyzOutputFile = 'Benzene_structure/benzene_rotated_60deg.xyz'
rotTheta = 60. * degrees_to_radians

### Read an XYZ file

In [84]:
xyz_file = open('Benzene_structure/benzene.xyz','r')
lineCount = 0
atomCount = 0
atomNames = []

for line in xyz_file:
    if lineCount == 0:
        nAtoms = int(line)
        positions = np.empty((nAtoms,3),dtype=float) # np.empty creates an empty numpy.ndarray that can be filled
    elif lineCount > 1:  # we want to skip over the 2nd line (lineCount = 1) because it holds no important information
        split_line = line.split()
        atomNames.append(split_line[0])
        for k in range(3):
            positions[atomCount,k] = float(split_line[k+1])
        atomCount += 1
    lineCount += 1

xyz_file.close()

print atomCount, lineCount
print atomNames
print positions

12 14
['C1', 'H1', 'C2', 'H2', 'C3', 'H3', 'C4', 'H4', 'C5', 'H5', 'C6', 'H6']
[[ 1.45   0.     0.   ]
 [ 2.45   0.     0.   ]
 [ 0.75  -1.212  0.   ]
 [ 1.25  -2.078  0.   ]
 [-0.75  -1.212  0.   ]
 [-1.25  -2.078  0.   ]
 [-1.45   0.     0.   ]
 [-2.45   0.     0.   ]
 [-0.75   1.212  0.   ]
 [-1.25   2.078  0.   ]
 [ 0.75   1.212  0.   ]
 [ 1.25   2.078  0.   ]]


### Rotate the molecule (using prewritten functions)

In [85]:
positions = rotation_functions.rot_x(positions,rotTheta)
positions = rotation_functions.rot_y(positions,rotTheta)
positions = rotation_functions.rot_z(positions,rotTheta)
print positions

[[ 0.3625     -0.62786842  1.25573684]
 [ 0.6125     -1.06088112  2.12176224]
 [-0.79181139  0.15945757  1.17433045]
 [-1.36655039  0.28893471  1.98233215]
 [-1.16681139  0.80897662 -0.12470766]
 [-1.99155039  1.37146647 -0.18273136]
 [-0.3625      0.62786842 -1.25573684]
 [-0.6125      1.06088112 -2.12176224]
 [ 0.79181139 -0.15945757 -1.17433045]
 [ 1.36655039 -0.28893471 -1.98233215]
 [ 1.16681139 -0.80897662  0.12470766]
 [ 1.99155039 -1.37146647  0.18273136]]


#### Hint at randomizing the rotation: look into np.random.rand() and don't forget units! 

### Output the new positions

In [86]:
outputFile = open(xyzOutputFile,'w')
outputFile.write('%10d\n'%(nAtoms))
outputFile.write('Translated Molecule\n')
for atom in range(nAtoms):
    outputFile.write('%5s %10.5f %10.5f %10.5f\n'%(atomNames[atom],positions[atom,0],positions[atom,1],positions[atom,2]))
outputFile.close()

# Create an XYZ file with multiple copies of benzene w/ no overlaps 
## Code Outline: 
1) Read in the xyz file, saving atom names and original positions.

2) Based on the number of copies desired, shift the original atomic positions by a user-defined value. __This will require a more complex approach than was used above.__

3) Output an xyz file with the new positions. We'll need to edit this code a bit to fix naming of variables.

### User Defined variables

In [74]:
import numpy as np

shift = 5.00 # distance between each copy of benzene; to be applied in all three dimensions; units of angstroms
xyzInputFile = 'Benzene_structure/benzene.xyz'
xyzOutputFile = 'Benzene_structure/multi_benzene.xyz'
copies = 27 # should have an integer cube root; we're creating a cube of benzene.

### Read an XYZ file

In [75]:
xyz_file = open('Benzene_structure/benzene.xyz','r')
lineCount = 0
atomCount = 0
atomNames = []

for line in xyz_file:
    if lineCount == 0:
        nAtoms = int(line)
        positions = np.empty((nAtoms,3),dtype=float) # np.empty creates an empty numpy.ndarray that can be filled
    elif lineCount > 1:  # we want to skip over the 2nd line (lineCount = 1) because it holds no important information
        split_line = line.split()
        atomNames.append(split_line[0])
        for k in range(3):
            positions[atomCount,k] = float(split_line[k+1])
        atomCount += 1
    lineCount += 1

xyz_file.close()

print atomCount, lineCount
print atomNames
print positions

12 14
['C1', 'H1', 'C2', 'H2', 'C3', 'H3', 'C4', 'H4', 'C5', 'H5', 'C6', 'H6']
[[ 1.45   0.     0.   ]
 [ 2.45   0.     0.   ]
 [ 0.75  -1.212  0.   ]
 [ 1.25  -2.078  0.   ]
 [-0.75  -1.212  0.   ]
 [-1.25  -2.078  0.   ]
 [-1.45   0.     0.   ]
 [-2.45   0.     0.   ]
 [-0.75   1.212  0.   ]
 [-1.25   2.078  0.   ]
 [ 0.75   1.212  0.   ]
 [ 1.25   2.078  0.   ]]


### Shift atomic positions

In [76]:
multiAtomNames = atomNames*copies
nAtoms = len(multiAtomNames)
nXYZ = int(float(copies)**0.333333333)+1 # number of rows in each dimension
print multiAtomNames, len(multiAtomNames), nXYZ

['C1', 'H1', 'C2', 'H2', 'C3', 'H3', 'C4', 'H4', 'C5', 'H5', 'C6', 'H6', 'C1', 'H1', 'C2', 'H2', 'C3', 'H3', 'C4', 'H4', 'C5', 'H5', 'C6', 'H6', 'C1', 'H1', 'C2', 'H2', 'C3', 'H3', 'C4', 'H4', 'C5', 'H5', 'C6', 'H6', 'C1', 'H1', 'C2', 'H2', 'C3', 'H3', 'C4', 'H4', 'C5', 'H5', 'C6', 'H6', 'C1', 'H1', 'C2', 'H2', 'C3', 'H3', 'C4', 'H4', 'C5', 'H5', 'C6', 'H6', 'C1', 'H1', 'C2', 'H2', 'C3', 'H3', 'C4', 'H4', 'C5', 'H5', 'C6', 'H6', 'C1', 'H1', 'C2', 'H2', 'C3', 'H3', 'C4', 'H4', 'C5', 'H5', 'C6', 'H6', 'C1', 'H1', 'C2', 'H2', 'C3', 'H3', 'C4', 'H4', 'C5', 'H5', 'C6', 'H6', 'C1', 'H1', 'C2', 'H2', 'C3', 'H3', 'C4', 'H4', 'C5', 'H5', 'C6', 'H6', 'C1', 'H1', 'C2', 'H2', 'C3', 'H3', 'C4', 'H4', 'C5', 'H5', 'C6', 'H6', 'C1', 'H1', 'C2', 'H2', 'C3', 'H3', 'C4', 'H4', 'C5', 'H5', 'C6', 'H6', 'C1', 'H1', 'C2', 'H2', 'C3', 'H3', 'C4', 'H4', 'C5', 'H5', 'C6', 'H6', 'C1', 'H1', 'C2', 'H2', 'C3', 'H3', 'C4', 'H4', 'C5', 'H5', 'C6', 'H6', 'C1', 'H1', 'C2', 'H2', 'C3', 'H3', 'C4', 'H4', 'C5', 'H5', 'C6

In [77]:
shift_xyz = np.empty(3,dtype=float)
for x in range(nXYZ):
    shift_xyz[0] = x*shift
    for y in range(nXYZ):
        shift_xyz[1] = y*shift
        for z in range(nXYZ):
            shift_xyz[2] = z*shift
            if x == 0 and y == 0 and z == 0:
                multiPositions = positions
            else:
                newPositions = positions + shift_xyz
                multiPositions = np.append(multiPositions,newPositions,axis=0)

print len(multiPositions)/3

108


### Output the new positions

In [78]:
outputFile = open(xyzOutputFile,'w')
outputFile.write('%10d\n'%(nAtoms))
outputFile.write('Translated, Copied Molecules\n')
for atom in range(nAtoms):
    outputFile.write('%5s %10.5f %10.5f %10.5f\n'%(multiAtomNames[atom],multiPositions[atom,0],multiPositions[atom,1],multiPositions[atom,2]))
outputFile.close()